version: 2.1
orbs:
  bot: lifen/bot@0
jobs:
  build:
    docker:
      - image: cimg/python:3.12.5
    steps:
      - checkout
      - bot/docker-build-and-push:
          multiArchEnable: false
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: 
                - master
